# Generated by Django 5.1.6 on 2025-02-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=5),
        ),
        migrations.AddField(
            model_name='lead',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='loan_term',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='lead',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
