# Generated by Django 5.1.6 on 2025-02-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lead_monthly_payment_lead_total_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
    ]
